# Generated by Django 3.1.2 on 2021-10-03 08:00

import bullseyes_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photourl', models.ImageField(blank=True, upload_to=bullseyes_server.models.upload_to)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('altid', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photourl', models.ImageField(blank=True, upload_to=bullseyes_server.models.upload_to)),
                ('rank', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('altid', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
